<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>toast-message_You have requested to access _63d7a9</name>
   <tag></tag>
   <elementGuidId>55f9b34d-979d-4910-b92e-09afdecb597a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>toast-message.oxd-text.oxd-text--toast-message</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='app']/div/div/form/div/toast-message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>toast-message</value>
      <webElementGuid>e19fce62-7d1e-4fad-bfc9-afe55e797699</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>oxd-text oxd-text--toast-message</value>
      <webElementGuid>d126e458-5ad3-451d-9b9d-5eb898878780</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You have requested to access a critical Administrator function in OrangeHRM and are required to validate your credentials below</value>
      <webElementGuid>5f4a37bd-bf30-46cb-be36-b2c793efc5b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;app&quot;)/div[@class=&quot;orangehrm-admin-access-container&quot;]/div[@class=&quot;orangehrm-card-container&quot;]/form[@class=&quot;oxd-form&quot;]/div[@class=&quot;orangehrm-admin-access-note-container&quot;]/toast-message[@class=&quot;oxd-text oxd-text--toast-message&quot;]</value>
      <webElementGuid>8e7b0dd1-9a4e-44eb-a084-f1693d8f154d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='app']/div/div/form/div/toast-message</value>
      <webElementGuid>aca5d7da-30a1-43a4-80b2-c0721fc9c9b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//toast-message</value>
      <webElementGuid>b62a0011-7524-4a0a-a6fa-a36386ce6dc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//toast-message[(text() = 'You have requested to access a critical Administrator function in OrangeHRM and are required to validate your credentials below' or . = 'You have requested to access a critical Administrator function in OrangeHRM and are required to validate your credentials below')]</value>
      <webElementGuid>e84b1544-1a9f-409a-a945-b19a7b1ac2f0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
